// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIhwUqOtTQUyT2M_ycjjG05pykku0NJ8Q',
    appId: '1:926298181026:web:8ddc7afe95738a47f2f6fb',
    messagingSenderId: '926298181026',
    projectId: 'loja-virtual-2fb14',
    authDomain: 'loja-virtual-2fb14.firebaseapp.com',
    storageBucket: 'loja-virtual-2fb14.firebasestorage.app',
    measurementId: 'G-ZKT4Y8TLDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1tic8trpqUvVyU8Y9d9usVpAo411hI3s',
    appId: '1:926298181026:android:b090fc8f3496d259f2f6fb',
    messagingSenderId: '926298181026',
    projectId: 'loja-virtual-2fb14',
    storageBucket: 'loja-virtual-2fb14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6WDIQ504_E9cUphC23M3ur7EHFfRLwqM',
    appId: '1:926298181026:ios:7334457f5189d78af2f6fb',
    messagingSenderId: '926298181026',
    projectId: 'loja-virtual-2fb14',
    storageBucket: 'loja-virtual-2fb14.firebasestorage.app',
    iosBundleId: 'br.com.moschenmurilo.lojaVirtualPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6WDIQ504_E9cUphC23M3ur7EHFfRLwqM',
    appId: '1:926298181026:ios:7334457f5189d78af2f6fb',
    messagingSenderId: '926298181026',
    projectId: 'loja-virtual-2fb14',
    storageBucket: 'loja-virtual-2fb14.firebasestorage.app',
    iosBundleId: 'br.com.moschenmurilo.lojaVirtualPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIhwUqOtTQUyT2M_ycjjG05pykku0NJ8Q',
    appId: '1:926298181026:web:263da817304194dff2f6fb',
    messagingSenderId: '926298181026',
    projectId: 'loja-virtual-2fb14',
    authDomain: 'loja-virtual-2fb14.firebaseapp.com',
    storageBucket: 'loja-virtual-2fb14.firebasestorage.app',
    measurementId: 'G-R7K34TB0RH',
  );
}
