name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      android-emulator:
        image: reactivecircus/android-emulator:api-33
        options: >-
          --privileged
          --shm-size 2g
        ports:
          - 5554:5554
          - 5555:5555

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Generate mocks
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Start Android emulator
      run: |
        sdkmanager "system-images;android-33;google_apis;x86_64"
        echo "no" | avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64" --force
        emulator -avd test -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect &
        adb wait-for-device
        adb shell input keyevent 82

    - name: Run tests
      run: flutter test --coverage
